# Generated by Django 6.0.7 on 2026-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255, verbose_name='Nom et prénom')),
                ('sexe', models.CharField(max_length=50, verbose_name='Sexe')),
                ('age', models.IntegerField(verbose_name='Âge')),
                ('localite', models.CharField(max_length=255, verbose_name='Localité')),
                ('contact_telephonique', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact téléphonique')),
                ('langue_principale', models.CharField(max_length=100, verbose_name='Langue principale parlée')),
                ('niveau_instruction', models.CharField(max_length=100, verbose_name='Niveau d’instruction')),
                ('activite_principale', models.CharField(max_length=255, verbose_name='Activité principale')),
                ('experience', models.CharField(max_length=100, verbose_name='Expérience')),
                ('principales_cultures', models.TextField(verbose_name='Principales cultures pratiquées')),
                ('materiel_agricole', models.TextField(verbose_name='Matériel Agricole')),
                ('ressources_disponibles', models.TextField(verbose_name='Ressources disponibles')),
                ('methode_stockage', models.TextField(verbose_name='Méthode de stockage')),
                ('source_eau', models.CharField(max_length=255, verbose_name='Source d’eau utilisée')),
                ('periode_production', models.CharField(max_length=255, verbose_name='Période de production')),
                ('total_production_an', models.CharField(max_length=255, verbose_name='Total de production/an')),
                ('pertes_rencontrees', models.TextField(verbose_name='Les pertes rencontrées')),
                ('problemes_rencontres', models.TextField(verbose_name='Problèmes/ difficultés rencontrés')),
            ],
        ),
    ]
