# Generated by Django 6.0.7 on 2026-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculteurs', '0002_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculteur',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, verbose_name='Sexe'),
        ),
    ]
