# Generated by Django 6.0.7 on 2026-07-28 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculteurs', '0003_alter_agriculteur_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculteur',
            name='code_unique',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Code unique / Pièce d'identité"),
        ),
        migrations.AddField(
            model_name='agriculteur',
            name='consentement_bailleur',
            field=models.BooleanField(default=False, verbose_name='Consentement accordé pour partager les données avec les bailleurs'),
        ),
        migrations.AddField(
            model_name='agriculteur',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agriculteur',
            name='notes_suivi',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de suivi (ex: Tracteur attribué)'),
        ),
        migrations.AddField(
            model_name='agriculteur',
            name='statut_traitement',
            field=models.CharField(choices=[('en_attente', '⏳ En attente'), ('en_cours', '🔄 En cours de traitement'), ('traite', '✅ Traité / Résolu')], default='en_attente', max_length=20, verbose_name='Statut du cas'),
        ),
    ]
